server:
  hostport: 127.0.0.1:8080
  scheme: http
  timeout: 10s

logger:
  level: info
  encoding: console
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: "msg"
    levelKey: "level"
    levelEncoder: "capitalColor"
    timeKey: "time"
    timeEncoder: "iso8601"

db:
  hostport: 127.0.0.1:26256
